"""initial_schema

Revision ID: e1d2c3f6f977
Revises: 
Create Date: 2026-08-07 16:11:33.679613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d2c3f6f977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('metrics_path', sa.String(length=1024), nullable=True),
    sa.Column('training_dataset', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models')),
    sa.UniqueConstraint('name', 'version', name='uq_ml_models_name_version')
    )
    op.create_index(op.f('ix_ml_models_algorithm'), 'ml_models', ['algorithm'], unique=False)
    op.create_index(op.f('ix_ml_models_is_active'), 'ml_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_index(op.f('ix_ml_models_version'), 'ml_models', ['version'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'INVESTIGATOR', 'REVIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', 'DEACTIVATED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=2048), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('feature_importances',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name=op.f('fk_feature_importances_model_id_ml_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_importances'))
    )
    op.create_index(op.f('ix_feature_importances_feature_name'), 'feature_importances', ['feature_name'], unique=False)
    op.create_index(op.f('ix_feature_importances_model_id'), 'feature_importances', ['model_id'], unique=False)
    op.create_index(op.f('ix_feature_importances_rank'), 'feature_importances', ['rank'], unique=False)
    op.create_table('settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('notification_preferences', sa.String(length=1024), nullable=False),
    sa.Column('dashboard_preferences', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_settings_user_id'))
    )
    op.create_table('training_jobs',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='trainingjobstatus', native_enum=False), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('epoch_count', sa.Integer(), nullable=True),
    sa.Column('training_accuracy', sa.Float(), nullable=True),
    sa.Column('validation_accuracy', sa.Float(), nullable=True),
    sa.Column('training_loss', sa.Float(), nullable=True),
    sa.Column('validation_loss', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('logs_path', sa.String(length=1024), nullable=True),
    sa.Column('hyperparameters', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name=op.f('fk_training_jobs_model_id_ml_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_jobs'))
    )
    op.create_index(op.f('ix_training_jobs_model_id'), 'training_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_started_at'), 'training_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_reference', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('merchant_category', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'REQUIRES_REVIEW', name='transactionstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_transactions_customer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_timestamp'), 'transactions', ['transaction_timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('predicted_label', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_predictions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_transaction_id'), 'predictions', ['transaction_id'], unique=True)
    op.create_table('fraud_alerts',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CLOSED', name='alertstatus', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_fraud_alerts_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_fraud_alerts_prediction_id_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_fraud_alerts_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_alerts'))
    )
    op.create_index(op.f('ix_fraud_alerts_assigned_to'), 'fraud_alerts', ['assigned_to'], unique=False)
    op.create_index('ix_fraud_alerts_created_at', 'fraud_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_prediction_id'), 'fraud_alerts', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_fraud_alerts_severity'), 'fraud_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_index('ix_fraud_alerts_transaction_id', 'fraud_alerts', ['transaction_id'], unique=False)
    op.create_table('investigation_cases',
    sa.Column('fraud_alert_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'ESCALATED', 'RESOLVED', name='casestatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_investigation_cases_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fraud_alert_id'], ['fraud_alerts.id'], name=op.f('fk_investigation_cases_fraud_alert_id_fraud_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_cases'))
    )
    op.create_index(op.f('ix_investigation_cases_assigned_to'), 'investigation_cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_investigation_cases_fraud_alert_id'), 'investigation_cases', ['fraud_alert_id'], unique=True)
    op.create_index(op.f('ix_investigation_cases_opened_at'), 'investigation_cases', ['opened_at'], unique=False)
    op.create_index(op.f('ix_investigation_cases_priority'), 'investigation_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_investigation_cases_status'), 'investigation_cases', ['status'], unique=False)
    op.create_table('case_comments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_case_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], name=op.f('fk_case_comments_case_id_investigation_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_comments'))
    )
    op.create_index(op.f('ix_case_comments_author_id'), 'case_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_case_comments_case_id'), 'case_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_comments_created_at'), 'case_comments', ['created_at'], unique=False)
    op.create_table('evidences',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], name=op.f('fk_evidences_case_id_investigation_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_evidences_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidences'))
    )
    op.create_index(op.f('ix_evidences_case_id'), 'evidences', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidences_uploaded_by'), 'evidences', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_uploaded_by'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_case_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_case_comments_created_at'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_case_id'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_author_id'), table_name='case_comments')
    op.drop_table('case_comments')
    op.drop_index(op.f('ix_investigation_cases_status'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_priority'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_opened_at'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_fraud_alert_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_assigned_to'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index('ix_fraud_alerts_transaction_id', table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_severity'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_prediction_id'), table_name='fraud_alerts')
    op.drop_index('ix_fraud_alerts_created_at', table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_assigned_to'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_predictions_transaction_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_transactions_transaction_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_started_at'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_model_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_table('settings')
    op.drop_index(op.f('ix_feature_importances_rank'), table_name='feature_importances')
    op.drop_index(op.f('ix_feature_importances_model_id'), table_name='feature_importances')
    op.drop_index(op.f('ix_feature_importances_feature_name'), table_name='feature_importances')
    op.drop_table('feature_importances')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ml_models_version'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_is_active'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_algorithm'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
